# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      src: ${{ steps.filter.outputs.src }}

    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            src:
              - 'src/**'
              - .pre-commit-config.yaml
              - pyproject.toml
              - tox.ini
            terraform:
                - 'terraform/**'

  test:
    needs: [ changes ]
    if: ${{ needs.changes.outputs.src == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox tox-uv
      - name: Lint and Test
        run: |
          python -m tox

  deploy:
    needs: [ changes, test ]
    if: ${{ always() }}
    # if: ${{ always() && needs.changes.outputs.terraform == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
      - name: terraform
        working-directory: terraform
        env:
          GOOGLE_PROJECT: "yukob-horse-racing"
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        run: |
          terraform fmt -check -diff
          terraform init -reconfigure -backend-config="gs.tfbackend"
          terraform validate
          terraform apply -auto-approve
