name: Deploy

on:
  push:
    branches: [ "main" ]

env:
  GCP_PROJECT: "yukob-horse-racing"
  REGION: "asia-northeast1"
  HORSE_RACING_IMAGE_NAME: "horse-racing"

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      src: ${{ steps.filter.outputs.src }}

    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            src:
              - 'src/**'
              - .pre-commit-config.yaml
              - pyproject.toml
              - tox.ini
            terraform:
                - 'terraform/**'

  test:
    needs: [ changes ]
    if: ${{ needs.changes.outputs.src == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox tox-uv
      - name: Lint and Test
        run: |
          python -m tox

  deploy:
    needs: [ changes, test ]
    if: ${{ always() }}
    # if: ${{ always() && needs.changes.outputs.terraform == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Install dependencies
        run: |
          uv sync

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: '>= 363.0.0'

      - name: Authorize Docker push
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Build and push docker image
        run: |
          REPOSITORY_NAME="${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}"
          docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT }}/${REPOSITORY_NAME}/${{ env.IMAGE_NAME }}:${{ github.sha }} .
          docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT }}/${REPOSITORY_NAME}/${{ env.IMAGE_NAME }}:${{ github.sha }}
        env:
          REGION: ${{ env.REGION }}
          GCP_PROJECT: ${{ env.GCP_PROJECT }}
          IMAGE_NAME: ${{ env.HORSE_RACING_IMAGE_NAME }}

      - name: terraform
        working-directory: terraform
        env:
          GOOGLE_PROJECT: "yukob-horse-racing"
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        run: |
          ls ../src/horse_racing/app/pipelines/*/*.yaml

          terraform fmt -check -diff
          terraform init -reconfigure -backend-config="gs.tfbackend"
          terraform validate
          terraform apply -auto-approve
