name: Deploy

on:
  push:
    branches: [ "main" ]

env:
  GCP_PROJECT: "yukob-horse-racing"
  REGION: "asia-northeast1"
  HORSE_RACING_IMAGE_NAME: "horse-racing"

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      src: ${{ steps.filter.outputs.src }}

    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            src:
              - .github/workflows/deploy.yml
              - 'src/**'
              - Dockerfile
              - pyproject.toml
            ci:
              - .pre-commit-config.yaml
              - tox.ini
            terraform:
              - 'terraform/**'

  test:
    needs: [ changes ]
    if: ${{ needs.changes.outputs.src == 'true' || needs.changes.outputs.ci == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox tox-uv
      - name: Lint and Test
        run: |
          python -m tox

  deploy-docker:
    needs: [ changes, test ]
    if: ${{ needs.changes.outputs.src == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: '>= 363.0.0'

      - name: Authorize Docker push
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Get repository name
        run: |
          echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}" >> ${GITHUB_ENV}

      - name: Build docker image
        run: |
          docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT }}/${{ env.REPOSITORY_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .
          docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT }}/${{ env.REPOSITORY_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
        env:
          REGION: ${{ env.REGION }}
          GCP_PROJECT: ${{ env.GCP_PROJECT }}
          IMAGE_NAME: ${{ env.HORSE_RACING_IMAGE_NAME }}

      - name: Build docker image
        run: |
          FULL_IMAGE=${{ env.REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT }}/${{ env.REPOSITORY_NAME }}/${{ env.IMAGE_NAME }}
          docker build -t $FULL_IMAGE:${{ github.sha }} .
          docker tag $FULL_IMAGE:${{ github.sha }} $FULL_IMAGE:latest
        env:
          IMAGE_NAME: ${{ env.HORSE_RACING_IMAGE_NAME }}

      - name: Push docker image
        run: |
          docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT }}/${{ env.REPOSITORY_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
        env:
          IMAGE_NAME: ${{ env.HORSE_RACING_IMAGE_NAME }}

      - name: Push docker image (latest)
        run: |
          docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT }}/${{ env.REPOSITORY_NAME }}/${{ env.IMAGE_NAME }}:latest
        env:
          IMAGE_NAME: ${{ env.HORSE_RACING_IMAGE_NAME }}

  deploy:
    needs: [ changes, deploy-docker ]
    if: ${{ always() }}
    # if: ${{ always() && needs.changes.outputs.terraform == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: |
          uv sync

      - name: terraform
        working-directory: terraform
        env:
          GOOGLE_PROJECT: "yukob-horse-racing"
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        run: |
          terraform fmt -check -diff
          terraform init -reconfigure -backend-config="gs.tfbackend"
          terraform validate
          terraform apply -auto-approve
